HW2, Дмитрий Цыкунов
kajigor/fl_2020_itmo_spr pull request #14
Opened 2020-03-01 23:47 UTC by ystid

2020-03-02 08:05 UTC, kajigor commented
У вас тесты падают

2020-03-02 13:07 UTC, ystid commented
Что-то исправил, но тесты (те, что на левую ассоциативность?) до сих пор падают. Сожалею об этом.

2020-03-02 13:45 UTC, kajigor requested changes

2020-03-02 13:45 UTC, kajigor commented on test/Test/Expr.hs
> +    -- Предполагаю, это и есть тесты на левую ассоциативность?
Это тесты на ошибку, которой у вас не было.

2020-03-02 13:45 UTC, kajigor commented on src/Expr.hs
> +sepBy1' sep elem = prsr `alt` some' elem
`sepBy1'` ведет себя странно:
```
op = return Plus 
num = symbol '1' >>= \_ -> return (Num 1)
p = sepBy1' op num 
```

```
λ> runParser p "111"
Success "" [
+
|_1
|_+
| |_1
| |_1]
```

А если сделать `op = return (Num 1)`, то на той же строке вообще ничего не завершится

2020-03-02 13:45 UTC, kajigor commented on test/Test/Expr.hs
> +    -- Предполагаю, это и есть тесты на левую ассоциативность?
Правую ассоциативность форсит, например, `evaluate "1-2-3" @?= Just (1-(2-3))`

2020-03-02 13:45 UTC, kajigor commented on src/Expr.hs
> +          return [BinOp op el (head elems)]
Не очень понимаю, зачем нужно делать списки, если списки везде сингтоны и вы оттуда берете первый элемент.

2020-03-04 20:16 UTC, ystid commented on test/Test/Expr.hs
> +    -- Предполагаю, это и есть тесты на левую ассоциативность?
Очень сильно запутался с ассоциативностями.
В итоге сделал так, как Вы говорили. Сделал операции более адекватными моим представлениям об арифметике и подкрутил тесты.

2020-03-04 20:17 UTC, ystid commented on src/Expr.hs
> +sepBy1' sep elem = prsr `alt` some' elem
Изначально ```sepBy1'``` планировалась, как приватная функция для ```parseMult``` в итоге убрал полностью, а настоящая в ```Combinators,hs```. 
Теперь полностью её убрал.

2020-03-04 20:18 UTC, ystid commented on src/Expr.hs
> +          return [BinOp op el (head elems)]
Хотел подстроить под существующую ```sepBy1'```. Убрал.

2020-03-05 17:55 UTC, kajigor requested changes

2020-03-05 17:55 UTC, kajigor commented on src/Expr.hs
> +parseSum = go `alt` parseBin `alt` parseMult
Тут очень много избыточности, которая порождает вообще неожиданную ассоциативность: `evaluate "1-2-3-4-5" @?= Just ((1-2)-((3-4)-5))`

2020-03-05 17:55 UTC, kajigor commented on src/Expr.hs
> +parseSum = go `alt` parseBin `alt` parseMult
В `parseMult` та же ситуация

2020-03-09 14:00 UTC, ystid commented
Кажется, разобрался. Теперь всё должно быть хорошо.

2020-03-10 06:49 UTC, kajigor commented on src/AST.hs
> +              | None
Ай-ай-ай. Люди изобрели `Maybe a` специально на такой случай.

2020-03-10 06:50 UTC, kajigor commented
Я поставлю за последнюю задачу половину балла, остальное ок

2020-03-10 06:50 UTC, closed without merging