HW3. Martyn Evgeny
kajigor/fl_2020_itmo_spr pull request #21
Opened 2020-03-08 20:26 UTC by dedok1997

2020-03-10 15:45 UTC, kajigor requested changes

2020-03-10 15:45 UTC, kajigor commented on src/Expr.hs
> +parseSum = uberExpr [ (sumOrMinus, LeftAssoc)
Мы для того писали `uberExpr`, чтобы руками приоритеты не расставлять.

2020-03-10 15:51 UTC, kajigor commented
Tex: 
1, 3 ok
2 не распознает требуемый язык: bbbb

2020-03-11 18:57 UTC, dedok1997 commented
Автомат для второго затехать не смог, залил фоткой.
uberParser - поправил.

2020-03-14 19:47 UTC, kajigor commented
На картинке не автомат

2020-03-14 19:47 UTC, kajigor requested changes

2020-03-14 19:47 UTC, kajigor commented on src/Expr.hs
> +parseSum = uberExpr [ (sum', LeftAssoc), (minus, LeftAssoc), (mult, LeftAssoc), (div', LeftAssoc)
Теперь у вас разные приоритеты у сложения и вычитания, а также умножения и деления: должны быть одинаковыми у каждой пары.

2020-03-14 20:02 UTC, dedok1997 commented on src/Expr.hs
> +parseSum = uberExpr [ (sum', LeftAssoc), (minus, LeftAssoc), (mult, LeftAssoc), (div', LeftAssoc)
Согласен. Но тогда не понятно, почему версия до этого не подходила

2020-03-14 20:05 UTC, kajigor commented on src/Expr.hs
> +parseSum = uberExpr [ (sum', LeftAssoc), (minus, LeftAssoc), (mult, LeftAssoc), (div', LeftAssoc)
Потому что `parseExpr` не должен использовать `parseSum` и `parseMult`

2020-03-14 20:09 UTC, kajigor commented
ok `parseExpr`

2020-03-14 20:17 UTC, dedok1997 commented
Картинку поправил

2020-03-18 14:32 UTC, kajigor commented
автомат ок

2020-03-18 14:32 UTC, closed without merging