HW3, Сидорова Елизавета
kajigor/fl_2020_itmo_spr pull request #22
Opened 2020-03-08 23:09 UTC by Liza858

2020-03-10 15:53 UTC, kajigor commented
Tex: 
1 не распознает требуемый язык: bbbaa
3 ok

2020-03-10 16:00 UTC, kajigor requested changes

2020-03-10 16:00 UTC, kajigor commented on src/UberExpr.hs
> +                           return $ opp op elem1 elem2
Не понимаю, зачем тут дублируется логика, присутствующая в `else`

2020-03-10 16:00 UTC, kajigor commented on src/UberExpr.hs
> +uberExpr xs parseElem opp = if (null $ tail $ xs) then do
`uberExpr` не будет работать в случае пустого списка парсеров операций

2020-03-10 16:00 UTC, kajigor commented on src/Expr.hs
> +parseSum = uberExpr [(parseAddOp <|> parseSubOp, LeftAssoc), (parseMultOp <|> parseDivOp, LeftAssoc)]
В задании надо было перереализовать `parseExpr`, ну да ладно

2020-03-14 04:35 UTC, Liza858 commented on src/Expr.hs
> +parseSum = uberExpr [(parseAddOp <|> parseSubOp, LeftAssoc), (parseMultOp <|> parseDivOp, LeftAssoc)]
Дописала

2020-03-14 04:35 UTC, Liza858 commented on src/UberExpr.hs
> +uberExpr xs parseElem opp = if (null $ tail $ xs) then do
Вроде исправила

2020-03-14 04:35 UTC, Liza858 commented on src/UberExpr.hs
> +                           return $ opp op elem1 elem2
Если я правильно поняла, что проблема -- в дублировании кода, то тоже вроде исправила

2020-03-14 20:00 UTC, kajigor commented
1 ok 
код ок

2020-03-14 20:00 UTC, closed without merging