HW3, Кальницкий Владимир
kajigor/fl_2020_itmo_spr pull request #23
Opened 2020-03-09 19:55 UTC by klntsky

2020-03-11 17:53 UTC, kajigor commented
тех: 
1 ок 
3 автомат не минимален

2020-03-11 17:55 UTC, kajigor commented
код: ок

2020-03-11 17:57 UTC, kajigor requested changes

2020-03-11 17:57 UTC, kajigor commented on src/Expr.hs
> +  parseMult
Мы для того писали `uberExpr`, чтобы руками не управлять приоритетами

2020-03-14 06:46 UTC, klntsky commented on src/Expr.hs
> +  parseMult
Я не понимаю.

>    * `[(Parser e i op, Associativity)]` -- список парсеров бинарных операторов с ассоциативностями в порядке повышения приоритета

У нас всё ещё нет способа задать одинаковые приоритеты.

2020-03-14 06:51 UTC, klntsky commented on src/Expr.hs
> +  parseMult
Я исправил так, чтобы тесты проходили, но мне кажется, то, что я сделал, меняет семантику.

2020-03-14 20:01 UTC, kajigor commented on src/Expr.hs
> +  parseMult
Есть: можно задавать более сложный парсер, чем парсящий один оператор

2020-03-14 20:03 UTC, kajigor commented
Автомат все еще не минимален

2020-03-14 20:16 UTC, klntsky commented on src/Expr.hs
> +  parseMult
В изначальной реализации так и было. Надо было сделать parseSum и parseMult независимыми друг от друга?

2020-03-14 20:26 UTC, klntsky commented
> Автомат все еще не минимален

Обновил

2020-03-18 14:34 UTC, kajigor commented on src/Expr.hs
> +  parseMult
`parseExpr` должен быть реализован через `uberExpr`, без использования `parseMult`, `parseSum`.

2020-03-18 14:34 UTC, kajigor commented
автомат ок

2020-03-18 14:47 UTC, kajigor commented on src/Expr.hs
> +  parseMult
Приоритет задается тем, в каком порядке операции в списке, при этом `+` и `-` (а также `*` и `\`) обладают одним приоритетом.

2020-03-23 07:52 UTC, closed without merging