HW4. Martyn Evgeny
kajigor/fl_2020_itmo_spr pull request #28
Opened 2020-03-15 13:54 UTC by dedok1997

2020-03-16 07:10 UTC, kajigor requested changes

2020-03-16 07:10 UTC, kajigor commented on test/Test/Keyword.hs
> +haskellKeywords = ["as", "case", "of", "class", "data", "default", "deriving", "do", "forall", "foreign", "hiding", "if", "then", "else", "import", "infix", "infixl", "infixr", "instance", "let", "in
Мы говорили, что `"data family"` и иже с ним выкидываются только в тесте про суффикс

2020-03-16 08:51 UTC, dedok1997 commented on test/Test/Keyword.hs
> +haskellKeywords = ["as", "case", "of", "class", "data", "default", "deriving", "do", "forall", "foreign", "hiding", "if", "then", "else", "import", "infix", "infixl", "infixr", "instance", "let", "in
Обновил тесты

2020-03-16 14:47 UTC, kajigor commented
Ключевые слова ок. 
1: у автомата на ребрах символы, а у вас -- выражения. Ничего не доказано. 
2: строки -- последовательности символов, а у вас -- выражений. Ничего не доказано

2020-03-16 14:51 UTC, dedok1997 commented
а 3 задание?

2020-03-18 14:44 UTC, kajigor commented
тех: 3, 4 ок

2020-03-18 14:44 UTC, closed without merging