HW04, Цыкунов Дмитрий
kajigor/fl_2020_itmo_spr pull request #31
Opened 2020-03-15 23:36 UTC by ystid

Не сомневаюсь, что можно было сделать эффективнее.

+ Подменил тест с суффиксом.

2020-03-16 15:33 UTC, kajigor requested changes

2020-03-16 15:33 UTC, kajigor commented on test/Test/Keyword.hs
> +      mapM_ (\str -> isFailure (runParser (keyword kw) (str ++ suffix)) @?= False) kw
Это что вообще?

2020-03-16 16:09 UTC, ystid commented on test/Test/Keyword.hs
> +      mapM_ (\str -> isFailure (runParser (keyword kw) (str ++ suffix)) @?= False) kw
Починил, теперь должно быть лучше.

2020-03-16 16:09 UTC, ystid commented
Прошу прощения за множество коммитов, всё еще играюсь с ```rebase```.

2020-03-18 15:00 UTC, kajigor commented
Tex:
2. ок
3. Строки -- последовательности символов алфавита, а не регулярных выражений. Ничего не доказали. 
4. ок (без минимальности)

2020-03-18 15:03 UTC, kajigor commented
`keyword` ok

2020-03-18 15:03 UTC, closed without merging