HW5, Бобров Артём
kajigor/fl_2020_itmo_spr pull request #36
Opened 2020-03-22 00:51 UTC by artbobrov

2020-03-23 09:05 UTC, kajigor requested changes

2020-03-23 09:05 UTC, kajigor commented on src/Expr.hs
> +      , (Lt <$ mapM symbol "<", NoAssoc)
Операции с одним приоритетом должны быть одним элементом списка

2020-03-23 09:05 UTC, kajigor commented on hw/LLanguageReference.md
> +
Не хватает информации о том, какую роль играют пробелы.

2020-03-23 09:05 UTC, kajigor commented on hw/LLanguageReference.md
> +Identifier ::= Letter Identifier | '_' Identifier | Identifier Digit
Не допускает индентификатор `a1_2`

2020-03-23 18:21 UTC, artbobrov commented
исправил

2020-03-24 09:13 UTC, kajigor commented
ok

2020-03-24 09:13 UTC, closed without merging