HW05. Дмитрий Орехов
kajigor/fl_2020_itmo_spr pull request #37
Opened 2020-03-22 19:08 UTC by DimaOrekhov

2020-03-22 19:09 UTC, DimaOrekhov commented
Спецификация лежит в корневой папке.

2020-03-23 09:23 UTC, kajigor requested changes

2020-03-23 09:23 UTC, kajigor commented on src/Expr.hs
> +                     _   -> error "signAsAction failed"
Не понимаю, зачем тут эта логика. Особенно, учитывая, что она в любой непонятной ситуации кидает в пользователя исключением

2020-03-23 09:23 UTC, kajigor commented on src/Expr.hs
>  parseExpr :: Parser String String AST
Не очень понятно, почему пробелы в выражениях теперь допустимы, но нельзя ставить пробелы после унарного минуса.

2020-03-23 09:29 UTC, kajigor commented
Не очень понимаю мотивацию за использованием переноса как разделителя отдельных стейтментов, раз у вас почти везде есть либо точки с запятыми, либо скобки для блоков. Особенно учитывая, что из этого вытекает ограничение на использование переносов в длинных арифметических выражениях. Есть какой-то пример, где возникают неоднозначности?

2020-03-23 09:35 UTC, DimaOrekhov commented
> Не очень понимаю мотивацию за использованием переноса как разделителя отдельных стейтментов, раз у вас почти везде есть либо точки с запятыми, либо скобки для блоков. 

У меня написано, что их можно разделять, но не обязательно. То есть парсер съест newline и все будет хорошо. Но именно разделитель это ;.

Я это подчеркнул, потому что в других местах newline у меня нарушает корректность кода, то есть нельзя перенести строку посреди statement или expression.

2020-03-23 09:35 UTC, DimaOrekhov commented on src/Expr.hs
>  parseExpr :: Parser String String AST
Да, поправлю это.

2020-03-23 09:36 UTC, DimaOrekhov commented on src/Expr.hs
> +                     _   -> error "signAsAction failed"
Немного не понимаю, что именно вы имеете ввиду под "этой логикой"?

Хотелось бы какое-то более осмысленное сообщение об ошибке?

2020-03-23 09:52 UTC, DimaOrekhov commented on src/Expr.hs
>  parseExpr :: Parser String String AST
Добавил поддержку произвольного числа пробелов между минусом и числом.

Добавил соответствующие тест кейсы в unit_parseNegNum и unit_parseNegInExpr.

2020-03-23 11:08 UTC, DimaOrekhov commented on src/Expr.hs
> +                     _   -> error "signAsAction failed"
Кажется, вы имеете ввиду, что ничего кроме минуса не сможет спарситься, потому что парсит symbol '-'. Соответственно, можно вообще никакой case не делать и не проверять, что спарсилось. Я верно понял?

2020-03-23 11:23 UTC, DimaOrekhov commented on src/Expr.hs
> +                     _   -> error "signAsAction failed"
Переписал в соответствии с этим пониманием. Добавил пару тест кейсов в unit_parseNegNum.

2020-03-23 11:26 UTC, DimaOrekhov commented
> Особенно учитывая, что из этого вытекает ограничение на использование переносов в длинных арифметических выражениях.

Стоит добавить поддержку использования переносов внутри expression? Сейчас там можно только пробелы.

2020-03-23 15:02 UTC, kajigor commented
> > Особенно учитывая, что из этого вытекает ограничение на использование переносов в длинных арифметических выражениях.
> 
> Стоит добавить поддержку использования переносов внутри expression? Сейчас там можно только пробелы.

Да нет, не обязательно. Просто вдруг у вас был какой-то хитрый план, который я не поняла.

2020-03-23 15:03 UTC, kajigor commented
ok

2020-03-23 15:03 UTC, closed without merging