HW5. Martyn Evgeny
kajigor/fl_2020_itmo_spr pull request #38
Opened 2020-03-23 13:41 UTC by dedok1997

2020-03-23 13:55 UTC, dedok1997 commented
Ветка сломалась, все комиты видно. Починить не смог

2020-03-23 15:12 UTC, kajigor requested changes

2020-03-23 15:12 UTC, kajigor commented on grammar.md
> +While -> 'while' '(' Expr ')' '{' Statement+ '}'
Тут намеренно стейтменты друг от друга ничем не отделяются?

2020-03-23 15:12 UTC, kajigor commented
парсеры ок

2020-03-23 15:31 UTC, dedok1997 commented on grammar.md
> +While -> 'while' '(' Expr ')' '{' Statement+ '}'
Ой. забыл поменять Statement+ на Statements

2020-03-24 09:15 UTC, kajigor commented
ok

2020-03-24 09:15 UTC, closed without merging