HW05, Колмогорова Валерия
kajigor/fl_2020_itmo_spr pull request #39
Opened 2020-03-23 19:32 UTC by rerapony

2020-03-24 08:00 UTC, kajigor commented
Код не собирается: зависимость на `containers` надо добавить.

2020-03-24 08:03 UTC, kajigor requested changes

2020-03-24 08:03 UTC, kajigor commented on hw/programming_language.md
> +var :: любое слово над алфавитом
Даже `while`?

2020-03-24 08:03 UTC, kajigor commented on hw/programming_language.md
> +op :: '+' | '-' | '*' | '/' | '//'
`'//'` -- а это что?

2020-03-24 08:03 UTC, kajigor commented on hw/programming_language.md
> +boolean :: or | and | equals | not equals
На одном уровне все?

2020-03-24 08:03 UTC, kajigor commented on hw/programming_language.md
> +if :: 'if' '(' condition ')' 'begin' sequence 'end'
Ветка `else` или ветка `then` потеряна?

2020-04-06 17:27 UTC, rerapony commented
> Код не собирается: зависимость на `containers` надо добавить.

ага, не закоммитила

2020-04-06 17:51 UTC, rerapony commented on hw/programming_language.md
> +op :: '+' | '-' | '*' | '/' | '//'
целочисленное деление?

2020-04-06 17:52 UTC, rerapony commented on hw/programming_language.md
> +var :: любое слово над алфавитом
исключая ключевые слова, получается

2020-04-06 18:42 UTC, rerapony commented on hw/programming_language.md
> +boolean :: or | and | equals | not equals
добавила табличку

2020-04-06 18:42 UTC, rerapony commented on hw/programming_language.md
> +if :: 'if' '(' condition ')' 'begin' sequence 'end'
fixed

2020-04-12 15:20 UTC, kajigor commented
ok

2020-04-12 15:20 UTC, closed without merging