HW06. Кальницкий Владимир
kajigor/fl_2020_itmo_spr pull request #42
Opened 2020-03-30 10:22 UTC by klntsky

2020-04-02 12:26 UTC, kajigor requested changes

2020-04-02 12:26 UTC, kajigor commented on cs-spec.md
> +Пробелы допустимы везде.
Видимо, не везде: 

```
λ> runParser parseL "(write (x)) "
Success " " (Seq {statements = [Write {expr = 
x}]})
λ> runParser parseL "(write ( x)) "
Failure "Predicate failed"
```

2020-04-02 12:26 UTC, kajigor commented
`uberExpr` ok

2020-04-05 14:29 UTC, klntsky commented on cs-spec.md
> +Пробелы допустимы везде.
Исправил спецификацию.

2020-04-06 08:53 UTC, kajigor commented
Опять же: 

```
λ> runParser parseL "(x:=13)"
Failure "Predicate failed"
λ> runParser parseL "(x:= 13)"
Failure "Predicate failed"
λ> runParser parseL "(x := 13)"
Success "" (Seq {statements = [Assign {var = "x", expr = 
13}]})
λ> runParser parseL "(x :=13)"
Success "" (Seq {statements = [Assign {var = "x", expr = 
13}]})
```

После идентификатора, строго говоря, не обязательно должен быть пробел. Есть два варианта того, что может идти после: любой символ не из алфавита идентификаторов, или же любой символ, который может использоваться в операторах, или скобки.

2020-04-12 15:23 UTC, kajigor commented
ok

2020-04-12 15:23 UTC, closed without merging