[FL_IFMO] ДЗ1. Цыкунов Дмитрий
kajigor/fl_2020_itmo_spr pull request #7
Opened 2020-02-17 22:11 UTC by ystid

2020-02-19 20:31 UTC, kajigor commented on src/Arith.hs
> +parseMult :: String -> Maybe (AST, String)
Этот парсер должен и деления парсить: 
`parseMult "1*2/3" @?= Just (BinOp Mult (Num 1) (BinOp Div (Num 2) (Num 3)), "")`

С этим изменением `parseExpr` должен стать проще

2020-02-19 20:33 UTC, kajigor requested changes

2020-02-19 20:33 UTC, kajigor commented on src/Arith.hs
> +      _ -> error "Something went horribly wrong"
У `Maybe a` есть специальное значение на этот случай

2020-02-19 20:33 UTC, kajigor commented on src/Arith.hs
> +parseMult :: String -> Maybe (AST, String)
Этот парсер должен и деления парсить:
`parseMult "1*2/3" @?= Just (BinOp Mult (Num 1) (BinOp Div (Num 2) (Num 3)), "")`

С этим изменением `parseExpr` должен стать проще

2020-02-24 10:08 UTC, kajigor requested changes

2020-02-24 10:08 UTC, kajigor commented on src/Arith.hs
> +      op | op `elem` [Mult, Div] -> do
Этот код не должен быть достижим, не правда ли?

2020-02-24 17:47 UTC, ystid commented on src/Arith.hs
> +      op | op `elem` [Mult, Div] -> do
Вы правы. Исправил.

2020-02-25 14:47 UTC, kajigor commented
ok

2020-02-25 14:47 UTC, closed without merging