HW1, Бобров Артём
kajigor/fl_2020_itmo_spr pull request #8
Opened 2020-02-17 23:03 UTC by artbobrov

2020-02-19 20:47 UTC, kajigor requested changes

2020-02-19 20:47 UTC, kajigor commented on src/Arith.hs
> +      (tree, rest'') <- parseMult rest'
Если `operator` не сложение или умножение, это вычисление сделано зря

2020-02-19 20:47 UTC, kajigor commented on src/Arith.hs
> +      (tree, rest'') <- parseSum rest'
То же замечание про `operator`

2020-02-19 20:52 UTC, artbobrov commented on src/Arith.hs
> +      (tree, rest'') <- parseSum rest'
Согласен, пофиксил

2020-02-19 20:52 UTC, artbobrov commented on src/Arith.hs
> +      (tree, rest'') <- parseMult rest'
Согласен, пофиксил

2020-02-20 15:12 UTC, kajigor approved these changes

2020-02-20 15:12 UTC, kajigor commented
ok, зачтено

2020-02-20 15:12 UTC, closed without merging